# Generated by Django 2.0 on 2017-12-14 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20171206_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.FileField(upload_to='static/oi/'),
        ),
    ]
