# Generated by Django 2.0 on 2017-12-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20171214_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.FileField(upload_to='casas/'),
        ),
    ]
