# Generated by Django 2.0 on 2017-12-14 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20171214_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='casa',
            name='foto',
            field=models.FileField(upload_to='images/casas/'),
        ),
    ]
